version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_to_sheets
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_to_sheets_data:/var/lib/postgresql/data

volumes:
  postgres_to_sheets_data:
